// Code generated by protoc-gen-go.
// source: applicationmaster_protocol.proto
// DO NOT EDIT!

package hadoop_yarn

import (
	json "encoding/json"

	proto "github.com/golang/protobuf/proto"

	math "math"
)

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

func init() {
}
