// Code generated by protoc-gen-go.
// source: yarn_protos.proto
// DO NOT EDIT!

package hadoop_yarn

import (
	json "encoding/json"

	proto "github.com/golang/protobuf/proto"

	math "math"

	hadoop_common "common/proto/hadoop/hadoop_common"
)

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type ContainerStateProto int32

const (
	ContainerStateProto_C_NEW      ContainerStateProto = 1
	ContainerStateProto_C_RUNNING  ContainerStateProto = 2
	ContainerStateProto_C_COMPLETE ContainerStateProto = 3
)

var ContainerStateProto_name = map[int32]string{
	1: "C_NEW",
	2: "C_RUNNING",
	3: "C_COMPLETE",
}
var ContainerStateProto_value = map[string]int32{
	"C_NEW":      1,
	"C_RUNNING":  2,
	"C_COMPLETE": 3,
}

func (x ContainerStateProto) Enum() *ContainerStateProto {
	p := new(ContainerStateProto)
	*p = x
	return p
}
func (x ContainerStateProto) String() string {
	return proto.EnumName(ContainerStateProto_name, int32(x))
}
func (x ContainerStateProto) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *ContainerStateProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ContainerStateProto_value, data, "ContainerStateProto")
	if err != nil {
		return err
	}
	*x = ContainerStateProto(value)
	return nil
}

type YarnApplicationStateProto int32

const (
	YarnApplicationStateProto_NEW        YarnApplicationStateProto = 1
	YarnApplicationStateProto_NEW_SAVING YarnApplicationStateProto = 2
	YarnApplicationStateProto_SUBMITTED  YarnApplicationStateProto = 3
	YarnApplicationStateProto_ACCEPTED   YarnApplicationStateProto = 4
	YarnApplicationStateProto_RUNNING    YarnApplicationStateProto = 5
	YarnApplicationStateProto_FINISHED   YarnApplicationStateProto = 6
	YarnApplicationStateProto_FAILED     YarnApplicationStateProto = 7
	YarnApplicationStateProto_KILLED     YarnApplicationStateProto = 8
)

var YarnApplicationStateProto_name = map[int32]string{
	1: "NEW",
	2: "NEW_SAVING",
	3: "SUBMITTED",
	4: "ACCEPTED",
	5: "RUNNING",
	6: "FINISHED",
	7: "FAILED",
	8: "KILLED",
}
var YarnApplicationStateProto_value = map[string]int32{
	"NEW":        1,
	"NEW_SAVING": 2,
	"SUBMITTED":  3,
	"ACCEPTED":   4,
	"RUNNING":    5,
	"FINISHED":   6,
	"FAILED":     7,
	"KILLED":     8,
}

func (x YarnApplicationStateProto) Enum() *YarnApplicationStateProto {
	p := new(YarnApplicationStateProto)
	*p = x
	return p
}
func (x YarnApplicationStateProto) String() string {
	return proto.EnumName(YarnApplicationStateProto_name, int32(x))
}
func (x YarnApplicationStateProto) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *YarnApplicationStateProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(YarnApplicationStateProto_value, data, "YarnApplicationStateProto")
	if err != nil {
		return err
	}
	*x = YarnApplicationStateProto(value)
	return nil
}

type YarnApplicationAttemptStateProto int32

const (
	YarnApplicationAttemptStateProto_APP_ATTEMPT_NEW              YarnApplicationAttemptStateProto = 1
	YarnApplicationAttemptStateProto_APP_ATTEMPT_SUBMITTED        YarnApplicationAttemptStateProto = 2
	YarnApplicationAttemptStateProto_APP_ATTEMPT_SCHEDULED        YarnApplicationAttemptStateProto = 3
	YarnApplicationAttemptStateProto_APP_ATTEMPT_ALLOCATED_SAVING YarnApplicationAttemptStateProto = 4
	YarnApplicationAttemptStateProto_APP_ATTEMPT_ALLOCATED        YarnApplicationAttemptStateProto = 5
	YarnApplicationAttemptStateProto_APP_ATTEMPT_LAUNCHED         YarnApplicationAttemptStateProto = 6
	YarnApplicationAttemptStateProto_APP_ATTEMPT_FAILED           YarnApplicationAttemptStateProto = 7
	YarnApplicationAttemptStateProto_APP_ATTEMPT_RUNNING          YarnApplicationAttemptStateProto = 8
	YarnApplicationAttemptStateProto_APP_ATTEMPT_FINISHING        YarnApplicationAttemptStateProto = 9
	YarnApplicationAttemptStateProto_APP_ATTEMPT_FINISHED         YarnApplicationAttemptStateProto = 10
	YarnApplicationAttemptStateProto_APP_ATTEMPT_KILLED           YarnApplicationAttemptStateProto = 11
)

var YarnApplicationAttemptStateProto_name = map[int32]string{
	1:  "APP_ATTEMPT_NEW",
	2:  "APP_ATTEMPT_SUBMITTED",
	3:  "APP_ATTEMPT_SCHEDULED",
	4:  "APP_ATTEMPT_ALLOCATED_SAVING",
	5:  "APP_ATTEMPT_ALLOCATED",
	6:  "APP_ATTEMPT_LAUNCHED",
	7:  "APP_ATTEMPT_FAILED",
	8:  "APP_ATTEMPT_RUNNING",
	9:  "APP_ATTEMPT_FINISHING",
	10: "APP_ATTEMPT_FINISHED",
	11: "APP_ATTEMPT_KILLED",
}
var YarnApplicationAttemptStateProto_value = map[string]int32{
	"APP_ATTEMPT_NEW":              1,
	"APP_ATTEMPT_SUBMITTED":        2,
	"APP_ATTEMPT_SCHEDULED":        3,
	"APP_ATTEMPT_ALLOCATED_SAVING": 4,
	"APP_ATTEMPT_ALLOCATED":        5,
	"APP_ATTEMPT_LAUNCHED":         6,
	"APP_ATTEMPT_FAILED":           7,
	"APP_ATTEMPT_RUNNING":          8,
	"APP_ATTEMPT_FINISHING":        9,
	"APP_ATTEMPT_FINISHED":         10,
	"APP_ATTEMPT_KILLED":           11,
}

func (x YarnApplicationAttemptStateProto) Enum() *YarnApplicationAttemptStateProto {
	p := new(YarnApplicationAttemptStateProto)
	*p = x
	return p
}
func (x YarnApplicationAttemptStateProto) String() string {
	return proto.EnumName(YarnApplicationAttemptStateProto_name, int32(x))
}
func (x YarnApplicationAttemptStateProto) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *YarnApplicationAttemptStateProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(YarnApplicationAttemptStateProto_value, data, "YarnApplicationAttemptStateProto")
	if err != nil {
		return err
	}
	*x = YarnApplicationAttemptStateProto(value)
	return nil
}

type FinalApplicationStatusProto int32

const (
	FinalApplicationStatusProto_APP_UNDEFINED FinalApplicationStatusProto = 0
	FinalApplicationStatusProto_APP_SUCCEEDED FinalApplicationStatusProto = 1
	FinalApplicationStatusProto_APP_FAILED    FinalApplicationStatusProto = 2
	FinalApplicationStatusProto_APP_KILLED    FinalApplicationStatusProto = 3
)

var FinalApplicationStatusProto_name = map[int32]string{
	0: "APP_UNDEFINED",
	1: "APP_SUCCEEDED",
	2: "APP_FAILED",
	3: "APP_KILLED",
}
var FinalApplicationStatusProto_value = map[string]int32{
	"APP_UNDEFINED": 0,
	"APP_SUCCEEDED": 1,
	"APP_FAILED":    2,
	"APP_KILLED":    3,
}

func (x FinalApplicationStatusProto) Enum() *FinalApplicationStatusProto {
	p := new(FinalApplicationStatusProto)
	*p = x
	return p
}
func (x FinalApplicationStatusProto) String() string {
	return proto.EnumName(FinalApplicationStatusProto_name, int32(x))
}
func (x FinalApplicationStatusProto) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *FinalApplicationStatusProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FinalApplicationStatusProto_value, data, "FinalApplicationStatusProto")
	if err != nil {
		return err
	}
	*x = FinalApplicationStatusProto(value)
	return nil
}

type LocalResourceVisibilityProto int32

const (
	LocalResourceVisibilityProto_PUBLIC      LocalResourceVisibilityProto = 1
	LocalResourceVisibilityProto_PRIVATE     LocalResourceVisibilityProto = 2
	LocalResourceVisibilityProto_APPLICATION LocalResourceVisibilityProto = 3
)

var LocalResourceVisibilityProto_name = map[int32]string{
	1: "PUBLIC",
	2: "PRIVATE",
	3: "APPLICATION",
}
var LocalResourceVisibilityProto_value = map[string]int32{
	"PUBLIC":      1,
	"PRIVATE":     2,
	"APPLICATION": 3,
}

func (x LocalResourceVisibilityProto) Enum() *LocalResourceVisibilityProto {
	p := new(LocalResourceVisibilityProto)
	*p = x
	return p
}
func (x LocalResourceVisibilityProto) String() string {
	return proto.EnumName(LocalResourceVisibilityProto_name, int32(x))
}
func (x LocalResourceVisibilityProto) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *LocalResourceVisibilityProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LocalResourceVisibilityProto_value, data, "LocalResourceVisibilityProto")
	if err != nil {
		return err
	}
	*x = LocalResourceVisibilityProto(value)
	return nil
}

type LocalResourceTypeProto int32

const (
	LocalResourceTypeProto_ARCHIVE LocalResourceTypeProto = 1
	LocalResourceTypeProto_FILE    LocalResourceTypeProto = 2
	LocalResourceTypeProto_PATTERN LocalResourceTypeProto = 3
)

var LocalResourceTypeProto_name = map[int32]string{
	1: "ARCHIVE",
	2: "FILE",
	3: "PATTERN",
}
var LocalResourceTypeProto_value = map[string]int32{
	"ARCHIVE": 1,
	"FILE":    2,
	"PATTERN": 3,
}

func (x LocalResourceTypeProto) Enum() *LocalResourceTypeProto {
	p := new(LocalResourceTypeProto)
	*p = x
	return p
}
func (x LocalResourceTypeProto) String() string {
	return proto.EnumName(LocalResourceTypeProto_name, int32(x))
}
func (x LocalResourceTypeProto) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *LocalResourceTypeProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LocalResourceTypeProto_value, data, "LocalResourceTypeProto")
	if err != nil {
		return err
	}
	*x = LocalResourceTypeProto(value)
	return nil
}

type NodeStateProto int32

const (
	NodeStateProto_NS_NEW            NodeStateProto = 1
	NodeStateProto_NS_RUNNING        NodeStateProto = 2
	NodeStateProto_NS_UNHEALTHY      NodeStateProto = 3
	NodeStateProto_NS_DECOMMISSIONED NodeStateProto = 4
	NodeStateProto_NS_LOST           NodeStateProto = 5
	NodeStateProto_NS_REBOOTED       NodeStateProto = 6
)

var NodeStateProto_name = map[int32]string{
	1: "NS_NEW",
	2: "NS_RUNNING",
	3: "NS_UNHEALTHY",
	4: "NS_DECOMMISSIONED",
	5: "NS_LOST",
	6: "NS_REBOOTED",
}
var NodeStateProto_value = map[string]int32{
	"NS_NEW":            1,
	"NS_RUNNING":        2,
	"NS_UNHEALTHY":      3,
	"NS_DECOMMISSIONED": 4,
	"NS_LOST":           5,
	"NS_REBOOTED":       6,
}

func (x NodeStateProto) Enum() *NodeStateProto {
	p := new(NodeStateProto)
	*p = x
	return p
}
func (x NodeStateProto) String() string {
	return proto.EnumName(NodeStateProto_name, int32(x))
}
func (x NodeStateProto) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *NodeStateProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(NodeStateProto_value, data, "NodeStateProto")
	if err != nil {
		return err
	}
	*x = NodeStateProto(value)
	return nil
}

type AMCommandProto int32

const (
	AMCommandProto_AM_RESYNC   AMCommandProto = 1
	AMCommandProto_AM_SHUTDOWN AMCommandProto = 2
)

var AMCommandProto_name = map[int32]string{
	1: "AM_RESYNC",
	2: "AM_SHUTDOWN",
}
var AMCommandProto_value = map[string]int32{
	"AM_RESYNC":   1,
	"AM_SHUTDOWN": 2,
}

func (x AMCommandProto) Enum() *AMCommandProto {
	p := new(AMCommandProto)
	*p = x
	return p
}
func (x AMCommandProto) String() string {
	return proto.EnumName(AMCommandProto_name, int32(x))
}
func (x AMCommandProto) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *AMCommandProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AMCommandProto_value, data, "AMCommandProto")
	if err != nil {
		return err
	}
	*x = AMCommandProto(value)
	return nil
}

type ApplicationAccessTypeProto int32

const (
	ApplicationAccessTypeProto_APPACCESS_VIEW_APP   ApplicationAccessTypeProto = 1
	ApplicationAccessTypeProto_APPACCESS_MODIFY_APP ApplicationAccessTypeProto = 2
)

var ApplicationAccessTypeProto_name = map[int32]string{
	1: "APPACCESS_VIEW_APP",
	2: "APPACCESS_MODIFY_APP",
}
var ApplicationAccessTypeProto_value = map[string]int32{
	"APPACCESS_VIEW_APP":   1,
	"APPACCESS_MODIFY_APP": 2,
}

func (x ApplicationAccessTypeProto) Enum() *ApplicationAccessTypeProto {
	p := new(ApplicationAccessTypeProto)
	*p = x
	return p
}
func (x ApplicationAccessTypeProto) String() string {
	return proto.EnumName(ApplicationAccessTypeProto_name, int32(x))
}
func (x ApplicationAccessTypeProto) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *ApplicationAccessTypeProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ApplicationAccessTypeProto_value, data, "ApplicationAccessTypeProto")
	if err != nil {
		return err
	}
	*x = ApplicationAccessTypeProto(value)
	return nil
}

type QueueStateProto int32

const (
	QueueStateProto_Q_STOPPED QueueStateProto = 1
	QueueStateProto_Q_RUNNING QueueStateProto = 2
)

var QueueStateProto_name = map[int32]string{
	1: "Q_STOPPED",
	2: "Q_RUNNING",
}
var QueueStateProto_value = map[string]int32{
	"Q_STOPPED": 1,
	"Q_RUNNING": 2,
}

func (x QueueStateProto) Enum() *QueueStateProto {
	p := new(QueueStateProto)
	*p = x
	return p
}
func (x QueueStateProto) String() string {
	return proto.EnumName(QueueStateProto_name, int32(x))
}
func (x QueueStateProto) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *QueueStateProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(QueueStateProto_value, data, "QueueStateProto")
	if err != nil {
		return err
	}
	*x = QueueStateProto(value)
	return nil
}

type QueueACLProto int32

const (
	QueueACLProto_QACL_SUBMIT_APPLICATIONS QueueACLProto = 1
	QueueACLProto_QACL_ADMINISTER_QUEUE    QueueACLProto = 2
)

var QueueACLProto_name = map[int32]string{
	1: "QACL_SUBMIT_APPLICATIONS",
	2: "QACL_ADMINISTER_QUEUE",
}
var QueueACLProto_value = map[string]int32{
	"QACL_SUBMIT_APPLICATIONS": 1,
	"QACL_ADMINISTER_QUEUE":    2,
}

func (x QueueACLProto) Enum() *QueueACLProto {
	p := new(QueueACLProto)
	*p = x
	return p
}
func (x QueueACLProto) String() string {
	return proto.EnumName(QueueACLProto_name, int32(x))
}
func (x QueueACLProto) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *QueueACLProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(QueueACLProto_value, data, "QueueACLProto")
	if err != nil {
		return err
	}
	*x = QueueACLProto(value)
	return nil
}

type ContainerExitStatusProto int32

const (
	ContainerExitStatusProto_SUCCESS      ContainerExitStatusProto = 0
	ContainerExitStatusProto_INVALID      ContainerExitStatusProto = -1000
	ContainerExitStatusProto_ABORTED      ContainerExitStatusProto = -100
	ContainerExitStatusProto_DISKS_FAILED ContainerExitStatusProto = -101
)

var ContainerExitStatusProto_name = map[int32]string{
	0:     "SUCCESS",
	-1000: "INVALID",
	-100:  "ABORTED",
	-101:  "DISKS_FAILED",
}
var ContainerExitStatusProto_value = map[string]int32{
	"SUCCESS":      0,
	"INVALID":      -1000,
	"ABORTED":      -100,
	"DISKS_FAILED": -101,
}

func (x ContainerExitStatusProto) Enum() *ContainerExitStatusProto {
	p := new(ContainerExitStatusProto)
	*p = x
	return p
}
func (x ContainerExitStatusProto) String() string {
	return proto.EnumName(ContainerExitStatusProto_name, int32(x))
}
func (x ContainerExitStatusProto) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *ContainerExitStatusProto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ContainerExitStatusProto_value, data, "ContainerExitStatusProto")
	if err != nil {
		return err
	}
	*x = ContainerExitStatusProto(value)
	return nil
}

type SerializedExceptionProto struct {
	Message          *string                   `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Trace            *string                   `protobuf:"bytes,2,opt,name=trace" json:"trace,omitempty"`
	ClassName        *string                   `protobuf:"bytes,3,opt,name=class_name" json:"class_name,omitempty"`
	Cause            *SerializedExceptionProto `protobuf:"bytes,4,opt,name=cause" json:"cause,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *SerializedExceptionProto) Reset()         { *m = SerializedExceptionProto{} }
func (m *SerializedExceptionProto) String() string { return proto.CompactTextString(m) }
func (*SerializedExceptionProto) ProtoMessage()    {}

func (m *SerializedExceptionProto) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *SerializedExceptionProto) GetTrace() string {
	if m != nil && m.Trace != nil {
		return *m.Trace
	}
	return ""
}

func (m *SerializedExceptionProto) GetClassName() string {
	if m != nil && m.ClassName != nil {
		return *m.ClassName
	}
	return ""
}

func (m *SerializedExceptionProto) GetCause() *SerializedExceptionProto {
	if m != nil {
		return m.Cause
	}
	return nil
}

type ApplicationIdProto struct {
	Id               *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	ClusterTimestamp *int64 `protobuf:"varint,2,opt,name=cluster_timestamp" json:"cluster_timestamp,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ApplicationIdProto) Reset()         { *m = ApplicationIdProto{} }
func (m *ApplicationIdProto) String() string { return proto.CompactTextString(m) }
func (*ApplicationIdProto) ProtoMessage()    {}

func (m *ApplicationIdProto) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ApplicationIdProto) GetClusterTimestamp() int64 {
	if m != nil && m.ClusterTimestamp != nil {
		return *m.ClusterTimestamp
	}
	return 0
}

type ApplicationAttemptIdProto struct {
	ApplicationId    *ApplicationIdProto `protobuf:"bytes,1,opt,name=application_id" json:"application_id,omitempty"`
	AttemptId        *int32              `protobuf:"varint,2,opt,name=attemptId" json:"attemptId,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ApplicationAttemptIdProto) Reset()         { *m = ApplicationAttemptIdProto{} }
func (m *ApplicationAttemptIdProto) String() string { return proto.CompactTextString(m) }
func (*ApplicationAttemptIdProto) ProtoMessage()    {}

func (m *ApplicationAttemptIdProto) GetApplicationId() *ApplicationIdProto {
	if m != nil {
		return m.ApplicationId
	}
	return nil
}

func (m *ApplicationAttemptIdProto) GetAttemptId() int32 {
	if m != nil && m.AttemptId != nil {
		return *m.AttemptId
	}
	return 0
}

type ContainerIdProto struct {
	AppId            *ApplicationIdProto        `protobuf:"bytes,1,opt,name=app_id" json:"app_id,omitempty"`
	AppAttemptId     *ApplicationAttemptIdProto `protobuf:"bytes,2,opt,name=app_attempt_id" json:"app_attempt_id,omitempty"`
	Id               *int32                     `protobuf:"varint,3,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *ContainerIdProto) Reset()         { *m = ContainerIdProto{} }
func (m *ContainerIdProto) String() string { return proto.CompactTextString(m) }
func (*ContainerIdProto) ProtoMessage()    {}

func (m *ContainerIdProto) GetAppId() *ApplicationIdProto {
	if m != nil {
		return m.AppId
	}
	return nil
}

func (m *ContainerIdProto) GetAppAttemptId() *ApplicationAttemptIdProto {
	if m != nil {
		return m.AppAttemptId
	}
	return nil
}

func (m *ContainerIdProto) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type ResourceProto struct {
	Memory           *int32 `protobuf:"varint,1,opt,name=memory" json:"memory,omitempty"`
	VirtualCores     *int32 `protobuf:"varint,2,opt,name=virtual_cores" json:"virtual_cores,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ResourceProto) Reset()         { *m = ResourceProto{} }
func (m *ResourceProto) String() string { return proto.CompactTextString(m) }
func (*ResourceProto) ProtoMessage()    {}

func (m *ResourceProto) GetMemory() int32 {
	if m != nil && m.Memory != nil {
		return *m.Memory
	}
	return 0
}

func (m *ResourceProto) GetVirtualCores() int32 {
	if m != nil && m.VirtualCores != nil {
		return *m.VirtualCores
	}
	return 0
}

type ResourceOptionProto struct {
	Resource          *ResourceProto `protobuf:"bytes,1,opt,name=resource" json:"resource,omitempty"`
	OverCommitTimeout *int32         `protobuf:"varint,2,opt,name=over_commit_timeout" json:"over_commit_timeout,omitempty"`
	XXX_unrecognized  []byte         `json:"-"`
}

func (m *ResourceOptionProto) Reset()         { *m = ResourceOptionProto{} }
func (m *ResourceOptionProto) String() string { return proto.CompactTextString(m) }
func (*ResourceOptionProto) ProtoMessage()    {}

func (m *ResourceOptionProto) GetResource() *ResourceProto {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *ResourceOptionProto) GetOverCommitTimeout() int32 {
	if m != nil && m.OverCommitTimeout != nil {
		return *m.OverCommitTimeout
	}
	return 0
}

type NodeResourceMapProto struct {
	NodeId           *NodeIdProto         `protobuf:"bytes,1,opt,name=node_id" json:"node_id,omitempty"`
	ResourceOption   *ResourceOptionProto `protobuf:"bytes,2,opt,name=resource_option" json:"resource_option,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *NodeResourceMapProto) Reset()         { *m = NodeResourceMapProto{} }
func (m *NodeResourceMapProto) String() string { return proto.CompactTextString(m) }
func (*NodeResourceMapProto) ProtoMessage()    {}

func (m *NodeResourceMapProto) GetNodeId() *NodeIdProto {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *NodeResourceMapProto) GetResourceOption() *ResourceOptionProto {
	if m != nil {
		return m.ResourceOption
	}
	return nil
}

type PriorityProto struct {
	Priority         *int32 `protobuf:"varint,1,opt,name=priority" json:"priority,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PriorityProto) Reset()         { *m = PriorityProto{} }
func (m *PriorityProto) String() string { return proto.CompactTextString(m) }
func (*PriorityProto) ProtoMessage()    {}

func (m *PriorityProto) GetPriority() int32 {
	if m != nil && m.Priority != nil {
		return *m.Priority
	}
	return 0
}

type ContainerProto struct {
	Id               *ContainerIdProto         `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	NodeId           *NodeIdProto              `protobuf:"bytes,2,opt,name=nodeId" json:"nodeId,omitempty"`
	NodeHttpAddress  *string                   `protobuf:"bytes,3,opt,name=node_http_address" json:"node_http_address,omitempty"`
	Resource         *ResourceProto            `protobuf:"bytes,4,opt,name=resource" json:"resource,omitempty"`
	Priority         *PriorityProto            `protobuf:"bytes,5,opt,name=priority" json:"priority,omitempty"`
	ContainerToken   *hadoop_common.TokenProto `protobuf:"bytes,6,opt,name=container_token" json:"container_token,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *ContainerProto) Reset()         { *m = ContainerProto{} }
func (m *ContainerProto) String() string { return proto.CompactTextString(m) }
func (*ContainerProto) ProtoMessage()    {}

func (m *ContainerProto) GetId() *ContainerIdProto {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ContainerProto) GetNodeId() *NodeIdProto {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *ContainerProto) GetNodeHttpAddress() string {
	if m != nil && m.NodeHttpAddress != nil {
		return *m.NodeHttpAddress
	}
	return ""
}

func (m *ContainerProto) GetResource() *ResourceProto {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *ContainerProto) GetPriority() *PriorityProto {
	if m != nil {
		return m.Priority
	}
	return nil
}

func (m *ContainerProto) GetContainerToken() *hadoop_common.TokenProto {
	if m != nil {
		return m.ContainerToken
	}
	return nil
}

type ContainerReportProto struct {
	ContainerId         *ContainerIdProto    `protobuf:"bytes,1,opt,name=container_id" json:"container_id,omitempty"`
	Resource            *ResourceProto       `protobuf:"bytes,2,opt,name=resource" json:"resource,omitempty"`
	NodeId              *NodeIdProto         `protobuf:"bytes,3,opt,name=node_id" json:"node_id,omitempty"`
	Priority            *PriorityProto       `protobuf:"bytes,4,opt,name=priority" json:"priority,omitempty"`
	CreationTime        *int64               `protobuf:"varint,5,opt,name=creation_time" json:"creation_time,omitempty"`
	FinishTime          *int64               `protobuf:"varint,6,opt,name=finish_time" json:"finish_time,omitempty"`
	DiagnosticsInfo     *string              `protobuf:"bytes,7,opt,name=diagnostics_info,def=N/A" json:"diagnostics_info,omitempty"`
	LogUrl              *string              `protobuf:"bytes,8,opt,name=log_url" json:"log_url,omitempty"`
	ContainerExitStatus *int32               `protobuf:"varint,9,opt,name=container_exit_status" json:"container_exit_status,omitempty"`
	ContainerState      *ContainerStateProto `protobuf:"varint,10,opt,name=container_state,enum=hadoop.yarn.ContainerStateProto" json:"container_state,omitempty"`
	XXX_unrecognized    []byte               `json:"-"`
}

func (m *ContainerReportProto) Reset()         { *m = ContainerReportProto{} }
func (m *ContainerReportProto) String() string { return proto.CompactTextString(m) }
func (*ContainerReportProto) ProtoMessage()    {}

const Default_ContainerReportProto_DiagnosticsInfo string = "N/A"

func (m *ContainerReportProto) GetContainerId() *ContainerIdProto {
	if m != nil {
		return m.ContainerId
	}
	return nil
}

func (m *ContainerReportProto) GetResource() *ResourceProto {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *ContainerReportProto) GetNodeId() *NodeIdProto {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *ContainerReportProto) GetPriority() *PriorityProto {
	if m != nil {
		return m.Priority
	}
	return nil
}

func (m *ContainerReportProto) GetCreationTime() int64 {
	if m != nil && m.CreationTime != nil {
		return *m.CreationTime
	}
	return 0
}

func (m *ContainerReportProto) GetFinishTime() int64 {
	if m != nil && m.FinishTime != nil {
		return *m.FinishTime
	}
	return 0
}

func (m *ContainerReportProto) GetDiagnosticsInfo() string {
	if m != nil && m.DiagnosticsInfo != nil {
		return *m.DiagnosticsInfo
	}
	return Default_ContainerReportProto_DiagnosticsInfo
}

func (m *ContainerReportProto) GetLogUrl() string {
	if m != nil && m.LogUrl != nil {
		return *m.LogUrl
	}
	return ""
}

func (m *ContainerReportProto) GetContainerExitStatus() int32 {
	if m != nil && m.ContainerExitStatus != nil {
		return *m.ContainerExitStatus
	}
	return 0
}

func (m *ContainerReportProto) GetContainerState() ContainerStateProto {
	if m != nil && m.ContainerState != nil {
		return *m.ContainerState
	}
	return 0
}

type URLProto struct {
	Scheme           *string `protobuf:"bytes,1,opt,name=scheme" json:"scheme,omitempty"`
	Host             *string `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
	Port             *int32  `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	File             *string `protobuf:"bytes,4,opt,name=file" json:"file,omitempty"`
	UserInfo         *string `protobuf:"bytes,5,opt,name=userInfo" json:"userInfo,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *URLProto) Reset()         { *m = URLProto{} }
func (m *URLProto) String() string { return proto.CompactTextString(m) }
func (*URLProto) ProtoMessage()    {}

func (m *URLProto) GetScheme() string {
	if m != nil && m.Scheme != nil {
		return *m.Scheme
	}
	return ""
}

func (m *URLProto) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *URLProto) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *URLProto) GetFile() string {
	if m != nil && m.File != nil {
		return *m.File
	}
	return ""
}

func (m *URLProto) GetUserInfo() string {
	if m != nil && m.UserInfo != nil {
		return *m.UserInfo
	}
	return ""
}

type LocalResourceProto struct {
	Resource         *URLProto                     `protobuf:"bytes,1,opt,name=resource" json:"resource,omitempty"`
	Size             *int64                        `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	Timestamp        *int64                        `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Type             *LocalResourceTypeProto       `protobuf:"varint,4,opt,name=type,enum=hadoop.yarn.LocalResourceTypeProto" json:"type,omitempty"`
	Visibility       *LocalResourceVisibilityProto `protobuf:"varint,5,opt,name=visibility,enum=hadoop.yarn.LocalResourceVisibilityProto" json:"visibility,omitempty"`
	Pattern          *string                       `protobuf:"bytes,6,opt,name=pattern" json:"pattern,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *LocalResourceProto) Reset()         { *m = LocalResourceProto{} }
func (m *LocalResourceProto) String() string { return proto.CompactTextString(m) }
func (*LocalResourceProto) ProtoMessage()    {}

func (m *LocalResourceProto) GetResource() *URLProto {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *LocalResourceProto) GetSize() int64 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *LocalResourceProto) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *LocalResourceProto) GetType() LocalResourceTypeProto {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *LocalResourceProto) GetVisibility() LocalResourceVisibilityProto {
	if m != nil && m.Visibility != nil {
		return *m.Visibility
	}
	return 0
}

func (m *LocalResourceProto) GetPattern() string {
	if m != nil && m.Pattern != nil {
		return *m.Pattern
	}
	return ""
}

type ApplicationResourceUsageReportProto struct {
	NumUsedContainers     *int32         `protobuf:"varint,1,opt,name=num_used_containers" json:"num_used_containers,omitempty"`
	NumReservedContainers *int32         `protobuf:"varint,2,opt,name=num_reserved_containers" json:"num_reserved_containers,omitempty"`
	UsedResources         *ResourceProto `protobuf:"bytes,3,opt,name=used_resources" json:"used_resources,omitempty"`
	ReservedResources     *ResourceProto `protobuf:"bytes,4,opt,name=reserved_resources" json:"reserved_resources,omitempty"`
	NeededResources       *ResourceProto `protobuf:"bytes,5,opt,name=needed_resources" json:"needed_resources,omitempty"`
	XXX_unrecognized      []byte         `json:"-"`
}

func (m *ApplicationResourceUsageReportProto) Reset()         { *m = ApplicationResourceUsageReportProto{} }
func (m *ApplicationResourceUsageReportProto) String() string { return proto.CompactTextString(m) }
func (*ApplicationResourceUsageReportProto) ProtoMessage()    {}

func (m *ApplicationResourceUsageReportProto) GetNumUsedContainers() int32 {
	if m != nil && m.NumUsedContainers != nil {
		return *m.NumUsedContainers
	}
	return 0
}

func (m *ApplicationResourceUsageReportProto) GetNumReservedContainers() int32 {
	if m != nil && m.NumReservedContainers != nil {
		return *m.NumReservedContainers
	}
	return 0
}

func (m *ApplicationResourceUsageReportProto) GetUsedResources() *ResourceProto {
	if m != nil {
		return m.UsedResources
	}
	return nil
}

func (m *ApplicationResourceUsageReportProto) GetReservedResources() *ResourceProto {
	if m != nil {
		return m.ReservedResources
	}
	return nil
}

func (m *ApplicationResourceUsageReportProto) GetNeededResources() *ResourceProto {
	if m != nil {
		return m.NeededResources
	}
	return nil
}

type ApplicationReportProto struct {
	ApplicationId               *ApplicationIdProto                  `protobuf:"bytes,1,opt,name=applicationId" json:"applicationId,omitempty"`
	User                        *string                              `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Queue                       *string                              `protobuf:"bytes,3,opt,name=queue" json:"queue,omitempty"`
	Name                        *string                              `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Host                        *string                              `protobuf:"bytes,5,opt,name=host" json:"host,omitempty"`
	RpcPort                     *int32                               `protobuf:"varint,6,opt,name=rpc_port" json:"rpc_port,omitempty"`
	ClientToAmToken             *hadoop_common.TokenProto            `protobuf:"bytes,7,opt,name=client_to_am_token" json:"client_to_am_token,omitempty"`
	YarnApplicationState        *YarnApplicationStateProto           `protobuf:"varint,8,opt,name=yarn_application_state,enum=hadoop.yarn.YarnApplicationStateProto" json:"yarn_application_state,omitempty"`
	TrackingUrl                 *string                              `protobuf:"bytes,9,opt,name=trackingUrl" json:"trackingUrl,omitempty"`
	Diagnostics                 *string                              `protobuf:"bytes,10,opt,name=diagnostics,def=N/A" json:"diagnostics,omitempty"`
	StartTime                   *int64                               `protobuf:"varint,11,opt,name=startTime" json:"startTime,omitempty"`
	FinishTime                  *int64                               `protobuf:"varint,12,opt,name=finishTime" json:"finishTime,omitempty"`
	FinalApplicationStatus      *FinalApplicationStatusProto         `protobuf:"varint,13,opt,name=final_application_status,enum=hadoop.yarn.FinalApplicationStatusProto" json:"final_application_status,omitempty"`
	AppResource_Usage           *ApplicationResourceUsageReportProto `protobuf:"bytes,14,opt,name=app_resource_Usage" json:"app_resource_Usage,omitempty"`
	OriginalTrackingUrl         *string                              `protobuf:"bytes,15,opt,name=originalTrackingUrl" json:"originalTrackingUrl,omitempty"`
	CurrentApplicationAttemptId *ApplicationAttemptIdProto           `protobuf:"bytes,16,opt,name=currentApplicationAttemptId" json:"currentApplicationAttemptId,omitempty"`
	Progress                    *float32                             `protobuf:"fixed32,17,opt,name=progress" json:"progress,omitempty"`
	ApplicationType             *string                              `protobuf:"bytes,18,opt,name=applicationType" json:"applicationType,omitempty"`
	AmRmToken                   *hadoop_common.TokenProto            `protobuf:"bytes,19,opt,name=am_rm_token" json:"am_rm_token,omitempty"`
	ApplicationTags             []string                             `protobuf:"bytes,20,rep,name=applicationTags" json:"applicationTags,omitempty"`
	XXX_unrecognized            []byte                               `json:"-"`
}

func (m *ApplicationReportProto) Reset()         { *m = ApplicationReportProto{} }
func (m *ApplicationReportProto) String() string { return proto.CompactTextString(m) }
func (*ApplicationReportProto) ProtoMessage()    {}

const Default_ApplicationReportProto_Diagnostics string = "N/A"

func (m *ApplicationReportProto) GetApplicationId() *ApplicationIdProto {
	if m != nil {
		return m.ApplicationId
	}
	return nil
}

func (m *ApplicationReportProto) GetUser() string {
	if m != nil && m.User != nil {
		return *m.User
	}
	return ""
}

func (m *ApplicationReportProto) GetQueue() string {
	if m != nil && m.Queue != nil {
		return *m.Queue
	}
	return ""
}

func (m *ApplicationReportProto) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ApplicationReportProto) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *ApplicationReportProto) GetRpcPort() int32 {
	if m != nil && m.RpcPort != nil {
		return *m.RpcPort
	}
	return 0
}

func (m *ApplicationReportProto) GetClientToAmToken() *hadoop_common.TokenProto {
	if m != nil {
		return m.ClientToAmToken
	}
	return nil
}

func (m *ApplicationReportProto) GetYarnApplicationState() YarnApplicationStateProto {
	if m != nil && m.YarnApplicationState != nil {
		return *m.YarnApplicationState
	}
	return 0
}

func (m *ApplicationReportProto) GetTrackingUrl() string {
	if m != nil && m.TrackingUrl != nil {
		return *m.TrackingUrl
	}
	return ""
}

func (m *ApplicationReportProto) GetDiagnostics() string {
	if m != nil && m.Diagnostics != nil {
		return *m.Diagnostics
	}
	return Default_ApplicationReportProto_Diagnostics
}

func (m *ApplicationReportProto) GetStartTime() int64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *ApplicationReportProto) GetFinishTime() int64 {
	if m != nil && m.FinishTime != nil {
		return *m.FinishTime
	}
	return 0
}

func (m *ApplicationReportProto) GetFinalApplicationStatus() FinalApplicationStatusProto {
	if m != nil && m.FinalApplicationStatus != nil {
		return *m.FinalApplicationStatus
	}
	return 0
}

func (m *ApplicationReportProto) GetAppResource_Usage() *ApplicationResourceUsageReportProto {
	if m != nil {
		return m.AppResource_Usage
	}
	return nil
}

func (m *ApplicationReportProto) GetOriginalTrackingUrl() string {
	if m != nil && m.OriginalTrackingUrl != nil {
		return *m.OriginalTrackingUrl
	}
	return ""
}

func (m *ApplicationReportProto) GetCurrentApplicationAttemptId() *ApplicationAttemptIdProto {
	if m != nil {
		return m.CurrentApplicationAttemptId
	}
	return nil
}

func (m *ApplicationReportProto) GetProgress() float32 {
	if m != nil && m.Progress != nil {
		return *m.Progress
	}
	return 0
}

func (m *ApplicationReportProto) GetApplicationType() string {
	if m != nil && m.ApplicationType != nil {
		return *m.ApplicationType
	}
	return ""
}

func (m *ApplicationReportProto) GetAmRmToken() *hadoop_common.TokenProto {
	if m != nil {
		return m.AmRmToken
	}
	return nil
}

func (m *ApplicationReportProto) GetApplicationTags() []string {
	if m != nil {
		return m.ApplicationTags
	}
	return nil
}

type ApplicationAttemptReportProto struct {
	ApplicationAttemptId        *ApplicationAttemptIdProto        `protobuf:"bytes,1,opt,name=application_attempt_id" json:"application_attempt_id,omitempty"`
	Host                        *string                           `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
	RpcPort                     *int32                            `protobuf:"varint,3,opt,name=rpc_port" json:"rpc_port,omitempty"`
	TrackingUrl                 *string                           `protobuf:"bytes,4,opt,name=tracking_url" json:"tracking_url,omitempty"`
	Diagnostics                 *string                           `protobuf:"bytes,5,opt,name=diagnostics,def=N/A" json:"diagnostics,omitempty"`
	YarnApplicationAttemptState *YarnApplicationAttemptStateProto `protobuf:"varint,6,opt,name=yarn_application_attempt_state,enum=hadoop.yarn.YarnApplicationAttemptStateProto" json:"yarn_application_attempt_state,omitempty"`
	AmContainerId               *ContainerIdProto                 `protobuf:"bytes,7,opt,name=am_container_id" json:"am_container_id,omitempty"`
	XXX_unrecognized            []byte                            `json:"-"`
}

func (m *ApplicationAttemptReportProto) Reset()         { *m = ApplicationAttemptReportProto{} }
func (m *ApplicationAttemptReportProto) String() string { return proto.CompactTextString(m) }
func (*ApplicationAttemptReportProto) ProtoMessage()    {}

const Default_ApplicationAttemptReportProto_Diagnostics string = "N/A"

func (m *ApplicationAttemptReportProto) GetApplicationAttemptId() *ApplicationAttemptIdProto {
	if m != nil {
		return m.ApplicationAttemptId
	}
	return nil
}

func (m *ApplicationAttemptReportProto) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *ApplicationAttemptReportProto) GetRpcPort() int32 {
	if m != nil && m.RpcPort != nil {
		return *m.RpcPort
	}
	return 0
}

func (m *ApplicationAttemptReportProto) GetTrackingUrl() string {
	if m != nil && m.TrackingUrl != nil {
		return *m.TrackingUrl
	}
	return ""
}

func (m *ApplicationAttemptReportProto) GetDiagnostics() string {
	if m != nil && m.Diagnostics != nil {
		return *m.Diagnostics
	}
	return Default_ApplicationAttemptReportProto_Diagnostics
}

func (m *ApplicationAttemptReportProto) GetYarnApplicationAttemptState() YarnApplicationAttemptStateProto {
	if m != nil && m.YarnApplicationAttemptState != nil {
		return *m.YarnApplicationAttemptState
	}
	return 0
}

func (m *ApplicationAttemptReportProto) GetAmContainerId() *ContainerIdProto {
	if m != nil {
		return m.AmContainerId
	}
	return nil
}

type NodeIdProto struct {
	Host             *string `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	Port             *int32  `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NodeIdProto) Reset()         { *m = NodeIdProto{} }
func (m *NodeIdProto) String() string { return proto.CompactTextString(m) }
func (*NodeIdProto) ProtoMessage()    {}

func (m *NodeIdProto) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *NodeIdProto) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

type NodeReportProto struct {
	NodeId               *NodeIdProto    `protobuf:"bytes,1,opt,name=nodeId" json:"nodeId,omitempty"`
	HttpAddress          *string         `protobuf:"bytes,2,opt,name=httpAddress" json:"httpAddress,omitempty"`
	RackName             *string         `protobuf:"bytes,3,opt,name=rackName" json:"rackName,omitempty"`
	Used                 *ResourceProto  `protobuf:"bytes,4,opt,name=used" json:"used,omitempty"`
	Capability           *ResourceProto  `protobuf:"bytes,5,opt,name=capability" json:"capability,omitempty"`
	NumContainers        *int32          `protobuf:"varint,6,opt,name=numContainers" json:"numContainers,omitempty"`
	NodeState            *NodeStateProto `protobuf:"varint,7,opt,name=node_state,enum=hadoop.yarn.NodeStateProto" json:"node_state,omitempty"`
	HealthReport         *string         `protobuf:"bytes,8,opt,name=health_report" json:"health_report,omitempty"`
	LastHealthReportTime *int64          `protobuf:"varint,9,opt,name=last_health_report_time" json:"last_health_report_time,omitempty"`
	XXX_unrecognized     []byte          `json:"-"`
}

func (m *NodeReportProto) Reset()         { *m = NodeReportProto{} }
func (m *NodeReportProto) String() string { return proto.CompactTextString(m) }
func (*NodeReportProto) ProtoMessage()    {}

func (m *NodeReportProto) GetNodeId() *NodeIdProto {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *NodeReportProto) GetHttpAddress() string {
	if m != nil && m.HttpAddress != nil {
		return *m.HttpAddress
	}
	return ""
}

func (m *NodeReportProto) GetRackName() string {
	if m != nil && m.RackName != nil {
		return *m.RackName
	}
	return ""
}

func (m *NodeReportProto) GetUsed() *ResourceProto {
	if m != nil {
		return m.Used
	}
	return nil
}

func (m *NodeReportProto) GetCapability() *ResourceProto {
	if m != nil {
		return m.Capability
	}
	return nil
}

func (m *NodeReportProto) GetNumContainers() int32 {
	if m != nil && m.NumContainers != nil {
		return *m.NumContainers
	}
	return 0
}

func (m *NodeReportProto) GetNodeState() NodeStateProto {
	if m != nil && m.NodeState != nil {
		return *m.NodeState
	}
	return 0
}

func (m *NodeReportProto) GetHealthReport() string {
	if m != nil && m.HealthReport != nil {
		return *m.HealthReport
	}
	return ""
}

func (m *NodeReportProto) GetLastHealthReportTime() int64 {
	if m != nil && m.LastHealthReportTime != nil {
		return *m.LastHealthReportTime
	}
	return 0
}

// //////////////////////////////////////////////////////////////////////
// //// From AM_RM_Protocol /////////////////////////////////////////////
// //////////////////////////////////////////////////////////////////////
type ResourceRequestProto struct {
	Priority         *PriorityProto `protobuf:"bytes,1,opt,name=priority" json:"priority,omitempty"`
	ResourceName     *string        `protobuf:"bytes,2,opt,name=resource_name" json:"resource_name,omitempty"`
	Capability       *ResourceProto `protobuf:"bytes,3,opt,name=capability" json:"capability,omitempty"`
	NumContainers    *int32         `protobuf:"varint,4,opt,name=num_containers" json:"num_containers,omitempty"`
	RelaxLocality    *bool          `protobuf:"varint,5,opt,name=relax_locality,def=1" json:"relax_locality,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *ResourceRequestProto) Reset()         { *m = ResourceRequestProto{} }
func (m *ResourceRequestProto) String() string { return proto.CompactTextString(m) }
func (*ResourceRequestProto) ProtoMessage()    {}

const Default_ResourceRequestProto_RelaxLocality bool = true

func (m *ResourceRequestProto) GetPriority() *PriorityProto {
	if m != nil {
		return m.Priority
	}
	return nil
}

func (m *ResourceRequestProto) GetResourceName() string {
	if m != nil && m.ResourceName != nil {
		return *m.ResourceName
	}
	return ""
}

func (m *ResourceRequestProto) GetCapability() *ResourceProto {
	if m != nil {
		return m.Capability
	}
	return nil
}

func (m *ResourceRequestProto) GetNumContainers() int32 {
	if m != nil && m.NumContainers != nil {
		return *m.NumContainers
	}
	return 0
}

func (m *ResourceRequestProto) GetRelaxLocality() bool {
	if m != nil && m.RelaxLocality != nil {
		return *m.RelaxLocality
	}
	return Default_ResourceRequestProto_RelaxLocality
}

type PreemptionMessageProto struct {
	StrictContract   *StrictPreemptionContractProto `protobuf:"bytes,1,opt,name=strictContract" json:"strictContract,omitempty"`
	Contract         *PreemptionContractProto       `protobuf:"bytes,2,opt,name=contract" json:"contract,omitempty"`
	XXX_unrecognized []byte                         `json:"-"`
}

func (m *PreemptionMessageProto) Reset()         { *m = PreemptionMessageProto{} }
func (m *PreemptionMessageProto) String() string { return proto.CompactTextString(m) }
func (*PreemptionMessageProto) ProtoMessage()    {}

func (m *PreemptionMessageProto) GetStrictContract() *StrictPreemptionContractProto {
	if m != nil {
		return m.StrictContract
	}
	return nil
}

func (m *PreemptionMessageProto) GetContract() *PreemptionContractProto {
	if m != nil {
		return m.Contract
	}
	return nil
}

type StrictPreemptionContractProto struct {
	Container        []*PreemptionContainerProto `protobuf:"bytes,1,rep,name=container" json:"container,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *StrictPreemptionContractProto) Reset()         { *m = StrictPreemptionContractProto{} }
func (m *StrictPreemptionContractProto) String() string { return proto.CompactTextString(m) }
func (*StrictPreemptionContractProto) ProtoMessage()    {}

func (m *StrictPreemptionContractProto) GetContainer() []*PreemptionContainerProto {
	if m != nil {
		return m.Container
	}
	return nil
}

type PreemptionContractProto struct {
	Resource         []*PreemptionResourceRequestProto `protobuf:"bytes,1,rep,name=resource" json:"resource,omitempty"`
	Container        []*PreemptionContainerProto       `protobuf:"bytes,2,rep,name=container" json:"container,omitempty"`
	XXX_unrecognized []byte                            `json:"-"`
}

func (m *PreemptionContractProto) Reset()         { *m = PreemptionContractProto{} }
func (m *PreemptionContractProto) String() string { return proto.CompactTextString(m) }
func (*PreemptionContractProto) ProtoMessage()    {}

func (m *PreemptionContractProto) GetResource() []*PreemptionResourceRequestProto {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *PreemptionContractProto) GetContainer() []*PreemptionContainerProto {
	if m != nil {
		return m.Container
	}
	return nil
}

type PreemptionContainerProto struct {
	Id               *ContainerIdProto `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *PreemptionContainerProto) Reset()         { *m = PreemptionContainerProto{} }
func (m *PreemptionContainerProto) String() string { return proto.CompactTextString(m) }
func (*PreemptionContainerProto) ProtoMessage()    {}

func (m *PreemptionContainerProto) GetId() *ContainerIdProto {
	if m != nil {
		return m.Id
	}
	return nil
}

type PreemptionResourceRequestProto struct {
	Resource         *ResourceRequestProto `protobuf:"bytes,1,opt,name=resource" json:"resource,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *PreemptionResourceRequestProto) Reset()         { *m = PreemptionResourceRequestProto{} }
func (m *PreemptionResourceRequestProto) String() string { return proto.CompactTextString(m) }
func (*PreemptionResourceRequestProto) ProtoMessage()    {}

func (m *PreemptionResourceRequestProto) GetResource() *ResourceRequestProto {
	if m != nil {
		return m.Resource
	}
	return nil
}

type ResourceBlacklistRequestProto struct {
	BlacklistAdditions []string `protobuf:"bytes,1,rep,name=blacklist_additions" json:"blacklist_additions,omitempty"`
	BlacklistRemovals  []string `protobuf:"bytes,2,rep,name=blacklist_removals" json:"blacklist_removals,omitempty"`
	XXX_unrecognized   []byte   `json:"-"`
}

func (m *ResourceBlacklistRequestProto) Reset()         { *m = ResourceBlacklistRequestProto{} }
func (m *ResourceBlacklistRequestProto) String() string { return proto.CompactTextString(m) }
func (*ResourceBlacklistRequestProto) ProtoMessage()    {}

func (m *ResourceBlacklistRequestProto) GetBlacklistAdditions() []string {
	if m != nil {
		return m.BlacklistAdditions
	}
	return nil
}

func (m *ResourceBlacklistRequestProto) GetBlacklistRemovals() []string {
	if m != nil {
		return m.BlacklistRemovals
	}
	return nil
}

// //////////////////////////////////////////////////////////////////////
// //// From client_RM_Protocol /////////////////////////////////////////
// //////////////////////////////////////////////////////////////////////
type ApplicationSubmissionContextProto struct {
	ApplicationId                           *ApplicationIdProto          `protobuf:"bytes,1,opt,name=application_id" json:"application_id,omitempty"`
	ApplicationName                         *string                      `protobuf:"bytes,2,opt,name=application_name,def=N/A" json:"application_name,omitempty"`
	Queue                                   *string                      `protobuf:"bytes,3,opt,name=queue,def=default" json:"queue,omitempty"`
	Priority                                *PriorityProto               `protobuf:"bytes,4,opt,name=priority" json:"priority,omitempty"`
	AmContainerSpec                         *ContainerLaunchContextProto `protobuf:"bytes,5,opt,name=am_container_spec" json:"am_container_spec,omitempty"`
	CancelTokensWhenComplete                *bool                        `protobuf:"varint,6,opt,name=cancel_tokens_when_complete,def=1" json:"cancel_tokens_when_complete,omitempty"`
	UnmanagedAm                             *bool                        `protobuf:"varint,7,opt,name=unmanaged_am,def=0" json:"unmanaged_am,omitempty"`
	MaxAppAttempts                          *int32                       `protobuf:"varint,8,opt,name=maxAppAttempts,def=0" json:"maxAppAttempts,omitempty"`
	Resource                                *ResourceProto               `protobuf:"bytes,9,opt,name=resource" json:"resource,omitempty"`
	ApplicationType                         *string                      `protobuf:"bytes,10,opt,name=applicationType,def=YARN" json:"applicationType,omitempty"`
	KeepContainersAcrossApplicationAttempts *bool                        `protobuf:"varint,11,opt,name=keep_containers_across_application_attempts,def=0" json:"keep_containers_across_application_attempts,omitempty"`
	ApplicationTags                         []string                     `protobuf:"bytes,12,rep,name=applicationTags" json:"applicationTags,omitempty"`
	XXX_unrecognized                        []byte                       `json:"-"`
}

func (m *ApplicationSubmissionContextProto) Reset()         { *m = ApplicationSubmissionContextProto{} }
func (m *ApplicationSubmissionContextProto) String() string { return proto.CompactTextString(m) }
func (*ApplicationSubmissionContextProto) ProtoMessage()    {}

const Default_ApplicationSubmissionContextProto_ApplicationName string = "N/A"
const Default_ApplicationSubmissionContextProto_Queue string = "default"
const Default_ApplicationSubmissionContextProto_CancelTokensWhenComplete bool = true
const Default_ApplicationSubmissionContextProto_UnmanagedAm bool = false
const Default_ApplicationSubmissionContextProto_MaxAppAttempts int32 = 0
const Default_ApplicationSubmissionContextProto_ApplicationType string = "YARN"
const Default_ApplicationSubmissionContextProto_KeepContainersAcrossApplicationAttempts bool = false

func (m *ApplicationSubmissionContextProto) GetApplicationId() *ApplicationIdProto {
	if m != nil {
		return m.ApplicationId
	}
	return nil
}

func (m *ApplicationSubmissionContextProto) GetApplicationName() string {
	if m != nil && m.ApplicationName != nil {
		return *m.ApplicationName
	}
	return Default_ApplicationSubmissionContextProto_ApplicationName
}

func (m *ApplicationSubmissionContextProto) GetQueue() string {
	if m != nil && m.Queue != nil {
		return *m.Queue
	}
	return Default_ApplicationSubmissionContextProto_Queue
}

func (m *ApplicationSubmissionContextProto) GetPriority() *PriorityProto {
	if m != nil {
		return m.Priority
	}
	return nil
}

func (m *ApplicationSubmissionContextProto) GetAmContainerSpec() *ContainerLaunchContextProto {
	if m != nil {
		return m.AmContainerSpec
	}
	return nil
}

func (m *ApplicationSubmissionContextProto) GetCancelTokensWhenComplete() bool {
	if m != nil && m.CancelTokensWhenComplete != nil {
		return *m.CancelTokensWhenComplete
	}
	return Default_ApplicationSubmissionContextProto_CancelTokensWhenComplete
}

func (m *ApplicationSubmissionContextProto) GetUnmanagedAm() bool {
	if m != nil && m.UnmanagedAm != nil {
		return *m.UnmanagedAm
	}
	return Default_ApplicationSubmissionContextProto_UnmanagedAm
}

func (m *ApplicationSubmissionContextProto) GetMaxAppAttempts() int32 {
	if m != nil && m.MaxAppAttempts != nil {
		return *m.MaxAppAttempts
	}
	return Default_ApplicationSubmissionContextProto_MaxAppAttempts
}

func (m *ApplicationSubmissionContextProto) GetResource() *ResourceProto {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *ApplicationSubmissionContextProto) GetApplicationType() string {
	if m != nil && m.ApplicationType != nil {
		return *m.ApplicationType
	}
	return Default_ApplicationSubmissionContextProto_ApplicationType
}

func (m *ApplicationSubmissionContextProto) GetKeepContainersAcrossApplicationAttempts() bool {
	if m != nil && m.KeepContainersAcrossApplicationAttempts != nil {
		return *m.KeepContainersAcrossApplicationAttempts
	}
	return Default_ApplicationSubmissionContextProto_KeepContainersAcrossApplicationAttempts
}

func (m *ApplicationSubmissionContextProto) GetApplicationTags() []string {
	if m != nil {
		return m.ApplicationTags
	}
	return nil
}

type ApplicationACLMapProto struct {
	AccessType       *ApplicationAccessTypeProto `protobuf:"varint,1,opt,name=accessType,enum=hadoop.yarn.ApplicationAccessTypeProto" json:"accessType,omitempty"`
	Acl              *string                     `protobuf:"bytes,2,opt,name=acl,def= " json:"acl,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *ApplicationACLMapProto) Reset()         { *m = ApplicationACLMapProto{} }
func (m *ApplicationACLMapProto) String() string { return proto.CompactTextString(m) }
func (*ApplicationACLMapProto) ProtoMessage()    {}

const Default_ApplicationACLMapProto_Acl string = " "

func (m *ApplicationACLMapProto) GetAccessType() ApplicationAccessTypeProto {
	if m != nil && m.AccessType != nil {
		return *m.AccessType
	}
	return 0
}

func (m *ApplicationACLMapProto) GetAcl() string {
	if m != nil && m.Acl != nil {
		return *m.Acl
	}
	return Default_ApplicationACLMapProto_Acl
}

type YarnClusterMetricsProto struct {
	NumNodeManagers  *int32 `protobuf:"varint,1,opt,name=num_node_managers" json:"num_node_managers,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *YarnClusterMetricsProto) Reset()         { *m = YarnClusterMetricsProto{} }
func (m *YarnClusterMetricsProto) String() string { return proto.CompactTextString(m) }
func (*YarnClusterMetricsProto) ProtoMessage()    {}

func (m *YarnClusterMetricsProto) GetNumNodeManagers() int32 {
	if m != nil && m.NumNodeManagers != nil {
		return *m.NumNodeManagers
	}
	return 0
}

type QueueInfoProto struct {
	QueueName        *string                   `protobuf:"bytes,1,opt,name=queueName" json:"queueName,omitempty"`
	Capacity         *float32                  `protobuf:"fixed32,2,opt,name=capacity" json:"capacity,omitempty"`
	MaximumCapacity  *float32                  `protobuf:"fixed32,3,opt,name=maximumCapacity" json:"maximumCapacity,omitempty"`
	CurrentCapacity  *float32                  `protobuf:"fixed32,4,opt,name=currentCapacity" json:"currentCapacity,omitempty"`
	State            *QueueStateProto          `protobuf:"varint,5,opt,name=state,enum=hadoop.yarn.QueueStateProto" json:"state,omitempty"`
	ChildQueues      []*QueueInfoProto         `protobuf:"bytes,6,rep,name=childQueues" json:"childQueues,omitempty"`
	Applications     []*ApplicationReportProto `protobuf:"bytes,7,rep,name=applications" json:"applications,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *QueueInfoProto) Reset()         { *m = QueueInfoProto{} }
func (m *QueueInfoProto) String() string { return proto.CompactTextString(m) }
func (*QueueInfoProto) ProtoMessage()    {}

func (m *QueueInfoProto) GetQueueName() string {
	if m != nil && m.QueueName != nil {
		return *m.QueueName
	}
	return ""
}

func (m *QueueInfoProto) GetCapacity() float32 {
	if m != nil && m.Capacity != nil {
		return *m.Capacity
	}
	return 0
}

func (m *QueueInfoProto) GetMaximumCapacity() float32 {
	if m != nil && m.MaximumCapacity != nil {
		return *m.MaximumCapacity
	}
	return 0
}

func (m *QueueInfoProto) GetCurrentCapacity() float32 {
	if m != nil && m.CurrentCapacity != nil {
		return *m.CurrentCapacity
	}
	return 0
}

func (m *QueueInfoProto) GetState() QueueStateProto {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

func (m *QueueInfoProto) GetChildQueues() []*QueueInfoProto {
	if m != nil {
		return m.ChildQueues
	}
	return nil
}

func (m *QueueInfoProto) GetApplications() []*ApplicationReportProto {
	if m != nil {
		return m.Applications
	}
	return nil
}

type QueueUserACLInfoProto struct {
	QueueName        *string         `protobuf:"bytes,1,opt,name=queueName" json:"queueName,omitempty"`
	UserAcls         []QueueACLProto `protobuf:"varint,2,rep,name=userAcls,enum=hadoop.yarn.QueueACLProto" json:"userAcls,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *QueueUserACLInfoProto) Reset()         { *m = QueueUserACLInfoProto{} }
func (m *QueueUserACLInfoProto) String() string { return proto.CompactTextString(m) }
func (*QueueUserACLInfoProto) ProtoMessage()    {}

func (m *QueueUserACLInfoProto) GetQueueName() string {
	if m != nil && m.QueueName != nil {
		return *m.QueueName
	}
	return ""
}

func (m *QueueUserACLInfoProto) GetUserAcls() []QueueACLProto {
	if m != nil {
		return m.UserAcls
	}
	return nil
}

type ContainerLaunchContextProto struct {
	LocalResources   []*StringLocalResourceMapProto `protobuf:"bytes,1,rep,name=localResources" json:"localResources,omitempty"`
	Tokens           []byte                         `protobuf:"bytes,2,opt,name=tokens" json:"tokens,omitempty"`
	ServiceData      []*StringBytesMapProto         `protobuf:"bytes,3,rep,name=service_data" json:"service_data,omitempty"`
	Environment      []*StringStringMapProto        `protobuf:"bytes,4,rep,name=environment" json:"environment,omitempty"`
	Command          []string                       `protobuf:"bytes,5,rep,name=command" json:"command,omitempty"`
	Application_ACLs []*ApplicationACLMapProto      `protobuf:"bytes,6,rep,name=application_ACLs" json:"application_ACLs,omitempty"`
	XXX_unrecognized []byte                         `json:"-"`
}

func (m *ContainerLaunchContextProto) Reset()         { *m = ContainerLaunchContextProto{} }
func (m *ContainerLaunchContextProto) String() string { return proto.CompactTextString(m) }
func (*ContainerLaunchContextProto) ProtoMessage()    {}

func (m *ContainerLaunchContextProto) GetLocalResources() []*StringLocalResourceMapProto {
	if m != nil {
		return m.LocalResources
	}
	return nil
}

func (m *ContainerLaunchContextProto) GetTokens() []byte {
	if m != nil {
		return m.Tokens
	}
	return nil
}

func (m *ContainerLaunchContextProto) GetServiceData() []*StringBytesMapProto {
	if m != nil {
		return m.ServiceData
	}
	return nil
}

func (m *ContainerLaunchContextProto) GetEnvironment() []*StringStringMapProto {
	if m != nil {
		return m.Environment
	}
	return nil
}

func (m *ContainerLaunchContextProto) GetCommand() []string {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *ContainerLaunchContextProto) GetApplication_ACLs() []*ApplicationACLMapProto {
	if m != nil {
		return m.Application_ACLs
	}
	return nil
}

type ContainerStatusProto struct {
	ContainerId      *ContainerIdProto    `protobuf:"bytes,1,opt,name=container_id" json:"container_id,omitempty"`
	State            *ContainerStateProto `protobuf:"varint,2,opt,name=state,enum=hadoop.yarn.ContainerStateProto" json:"state,omitempty"`
	Diagnostics      *string              `protobuf:"bytes,3,opt,name=diagnostics,def=N/A" json:"diagnostics,omitempty"`
	ExitStatus       *int32               `protobuf:"varint,4,opt,name=exit_status,def=-1000" json:"exit_status,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *ContainerStatusProto) Reset()         { *m = ContainerStatusProto{} }
func (m *ContainerStatusProto) String() string { return proto.CompactTextString(m) }
func (*ContainerStatusProto) ProtoMessage()    {}

const Default_ContainerStatusProto_Diagnostics string = "N/A"
const Default_ContainerStatusProto_ExitStatus int32 = -1000

func (m *ContainerStatusProto) GetContainerId() *ContainerIdProto {
	if m != nil {
		return m.ContainerId
	}
	return nil
}

func (m *ContainerStatusProto) GetState() ContainerStateProto {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

func (m *ContainerStatusProto) GetDiagnostics() string {
	if m != nil && m.Diagnostics != nil {
		return *m.Diagnostics
	}
	return Default_ContainerStatusProto_Diagnostics
}

func (m *ContainerStatusProto) GetExitStatus() int32 {
	if m != nil && m.ExitStatus != nil {
		return *m.ExitStatus
	}
	return Default_ContainerStatusProto_ExitStatus
}

type ContainerResourceIncreaseRequestProto struct {
	ContainerId      *ContainerIdProto `protobuf:"bytes,1,opt,name=container_id" json:"container_id,omitempty"`
	Capability       *ResourceProto    `protobuf:"bytes,2,opt,name=capability" json:"capability,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *ContainerResourceIncreaseRequestProto) Reset()         { *m = ContainerResourceIncreaseRequestProto{} }
func (m *ContainerResourceIncreaseRequestProto) String() string { return proto.CompactTextString(m) }
func (*ContainerResourceIncreaseRequestProto) ProtoMessage()    {}

func (m *ContainerResourceIncreaseRequestProto) GetContainerId() *ContainerIdProto {
	if m != nil {
		return m.ContainerId
	}
	return nil
}

func (m *ContainerResourceIncreaseRequestProto) GetCapability() *ResourceProto {
	if m != nil {
		return m.Capability
	}
	return nil
}

type ContainerResourceIncreaseProto struct {
	ContainerId      *ContainerIdProto         `protobuf:"bytes,1,opt,name=container_id" json:"container_id,omitempty"`
	Capability       *ResourceProto            `protobuf:"bytes,2,opt,name=capability" json:"capability,omitempty"`
	ContainerToken   *hadoop_common.TokenProto `protobuf:"bytes,3,opt,name=container_token" json:"container_token,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *ContainerResourceIncreaseProto) Reset()         { *m = ContainerResourceIncreaseProto{} }
func (m *ContainerResourceIncreaseProto) String() string { return proto.CompactTextString(m) }
func (*ContainerResourceIncreaseProto) ProtoMessage()    {}

func (m *ContainerResourceIncreaseProto) GetContainerId() *ContainerIdProto {
	if m != nil {
		return m.ContainerId
	}
	return nil
}

func (m *ContainerResourceIncreaseProto) GetCapability() *ResourceProto {
	if m != nil {
		return m.Capability
	}
	return nil
}

func (m *ContainerResourceIncreaseProto) GetContainerToken() *hadoop_common.TokenProto {
	if m != nil {
		return m.ContainerToken
	}
	return nil
}

type ContainerResourceDecreaseProto struct {
	ContainerId      *ContainerIdProto `protobuf:"bytes,1,opt,name=container_id" json:"container_id,omitempty"`
	Capability       *ResourceProto    `protobuf:"bytes,2,opt,name=capability" json:"capability,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *ContainerResourceDecreaseProto) Reset()         { *m = ContainerResourceDecreaseProto{} }
func (m *ContainerResourceDecreaseProto) String() string { return proto.CompactTextString(m) }
func (*ContainerResourceDecreaseProto) ProtoMessage()    {}

func (m *ContainerResourceDecreaseProto) GetContainerId() *ContainerIdProto {
	if m != nil {
		return m.ContainerId
	}
	return nil
}

func (m *ContainerResourceDecreaseProto) GetCapability() *ResourceProto {
	if m != nil {
		return m.Capability
	}
	return nil
}

// //////////////////////////////////////////////////////////////////////
// //// From common//////////////////////////////////////////////////////
// //////////////////////////////////////////////////////////////////////
type StringLocalResourceMapProto struct {
	Key              *string             `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value            *LocalResourceProto `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *StringLocalResourceMapProto) Reset()         { *m = StringLocalResourceMapProto{} }
func (m *StringLocalResourceMapProto) String() string { return proto.CompactTextString(m) }
func (*StringLocalResourceMapProto) ProtoMessage()    {}

func (m *StringLocalResourceMapProto) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *StringLocalResourceMapProto) GetValue() *LocalResourceProto {
	if m != nil {
		return m.Value
	}
	return nil
}

type StringStringMapProto struct {
	Key              *string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value            *string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StringStringMapProto) Reset()         { *m = StringStringMapProto{} }
func (m *StringStringMapProto) String() string { return proto.CompactTextString(m) }
func (*StringStringMapProto) ProtoMessage()    {}

func (m *StringStringMapProto) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *StringStringMapProto) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type StringBytesMapProto struct {
	Key              *string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value            []byte  `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StringBytesMapProto) Reset()         { *m = StringBytesMapProto{} }
func (m *StringBytesMapProto) String() string { return proto.CompactTextString(m) }
func (*StringBytesMapProto) ProtoMessage()    {}

func (m *StringBytesMapProto) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *StringBytesMapProto) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterEnum("hadoop.yarn.ContainerStateProto", ContainerStateProto_name, ContainerStateProto_value)
	proto.RegisterEnum("hadoop.yarn.YarnApplicationStateProto", YarnApplicationStateProto_name, YarnApplicationStateProto_value)
	proto.RegisterEnum("hadoop.yarn.YarnApplicationAttemptStateProto", YarnApplicationAttemptStateProto_name, YarnApplicationAttemptStateProto_value)
	proto.RegisterEnum("hadoop.yarn.FinalApplicationStatusProto", FinalApplicationStatusProto_name, FinalApplicationStatusProto_value)
	proto.RegisterEnum("hadoop.yarn.LocalResourceVisibilityProto", LocalResourceVisibilityProto_name, LocalResourceVisibilityProto_value)
	proto.RegisterEnum("hadoop.yarn.LocalResourceTypeProto", LocalResourceTypeProto_name, LocalResourceTypeProto_value)
	proto.RegisterEnum("hadoop.yarn.NodeStateProto", NodeStateProto_name, NodeStateProto_value)
	proto.RegisterEnum("hadoop.yarn.AMCommandProto", AMCommandProto_name, AMCommandProto_value)
	proto.RegisterEnum("hadoop.yarn.ApplicationAccessTypeProto", ApplicationAccessTypeProto_name, ApplicationAccessTypeProto_value)
	proto.RegisterEnum("hadoop.yarn.QueueStateProto", QueueStateProto_name, QueueStateProto_value)
	proto.RegisterEnum("hadoop.yarn.QueueACLProto", QueueACLProto_name, QueueACLProto_value)
	proto.RegisterEnum("hadoop.yarn.ContainerExitStatusProto", ContainerExitStatusProto_name, ContainerExitStatusProto_value)
}
